### ISSUE TITLE
BTV Transactions failing to connect

### ISSUE THREAD

**Issue by KewlCryptoTrader** [ymgve/bitcoin_fork_claimer#12]
Connecting to ('seed1.bitvote.one', 8333) ... SUCCESS!
---> 'version' (93 bytes)
Traceback (most recent call last):
  File "C:\Python27\claimer.py", line 1038, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "C:\Python27\claimer.py", line 428, in send_tx
    cmd, payload = client.recv_msg()
  File "C:\Python27\claimer.py", line 399, in recv_msg
    header = recv_all(24)
  File "C:\Python27\claimer.py", line 395, in recv_all
    raise socket.error("Connection reset!")
socket.error: Connection reset!

**Comment by ymgve** [comment]
Server disconnected you, nothing to do but try again.

**Comment by KewlCryptoTrader** [comment]
The transaction is not broadcasted though. Is the workaround to just keep trying?

**Comment by ymgve** [comment]
Yes. I can't do anything about the state of the various coin peer networks.

**Comment by ymgve** [comment]
Actually, I have to apologize. I looked into this issue now, and it seems like the BTV admins updated some parameters in their code to add replay protection and prevent the chain from hanging at block 505050.

I've updated the claimer script to work with these changes.

**Comment by KewlCryptoTrader** [comment]
Thanks. I appreciate all of the hard work you're putting into this script. It has worked great for me so far.
