### ISSUE TITLE
How can I find out, if a particular coin existed on the BTC main chain pre-fork?

### ISSUE THREAD

**Issue by Golddouble** [ymgve/bitcoin_fork_claimer#18]
In the read.me you write:

> In blockchain.info mode it uses the blockchain.info API to query and validate information about the transaction you're spending from. This only works for transferring/claiming coins that existed on the BTC main chain pre-fork.

I do not understand what this means.

Surely I want to claim all this coins:

    B2X - Segwit 2X
    BCD - Bitcoin Diamond
    BCH - Bitcoin Cash
    BCX - Bitcoin X
    BPA - Bitcoin Pizza
    BTF - Bitcoin Faith
    BTG - Bitcoin Gold
    BTH - Bitcoin Hot
    BTN - Bitcoin New
    BTP - Bitcoin Pay
    BTSQ - Bitcoin Community
    BTT - Bitcoin Top
    BTV - Bitcoin Vote
    BTW - Bitcoin World
    BTX - Bitcore
    SBTC - Super Bitcoin
    UBTC - United Bitcoin
    WBTC - World Bitcoin

So I must to know, which of them I can claim with the blockchain.info assisted mode, and which I have to claim with the standalone mode.

Can you please help me. Thank you.

**Comment by ymgve** [comment]
The only ones that doesn't work with blockchain.info mode at the moment is BTX and BTK.
