### ISSUE TITLE
Fees: Makes bitcoin_fork_claimer a BTC- transaction or a fork-coin transaction

### ISSUE THREAD

**Issue by Golddouble** [ymgve/bitcoin_fork_claimer#19]
You write in the read.me

> Default fee is set to 1000 satoshis, but can be changed with the --fee option.

Question:
For which transaction do we pay fee? Is this a BTC transaction which needs fees, or is this the fork-coin transaction which needs this fees? Does bitcoin_fork_claimer make a transaction on the blockchain of the fork coin?

Thank you for an answer.

**Comment by whizz** [comment]
It's the fees on the fork network. The script never touches BTC network, only forked blockchain. I hope you have moved all the BTC coins from the keys you work with, this is super important, unless you want to lose BTC.

Most networks require at least 1000 satoshi. You can try lower fees, I had success with 500 satoshi fees on some networks.

**Comment by Golddouble** [comment]
OK. Thank you @whizz.
