### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by NoWay426** [ymgve/bitcoin_fork_claimer#2]
New to scripts. Downloaded Python 2.7. Followed the script verbatim, however I keep getting invalid syntax error upon entry. Tried one space between inputs & two spaces. Double checked all data, can't see any errors in my inputs. Any ideas on where I may be messing up? Thanks in advance.

**Comment by Mugen-Kanosei** [comment]
Formatting should look like the following:

claimer.py <cointype> <source transaction ID> <source private key> <source address> <destination address>

claimer.py BTG 4adc427d330497992710feaa32f85c389ef5106f74e7006878bd14b54500dfff 5K2YUVmWfxbmvsNxCsfvArXdGXm7d5DC9pn4yD75k2UaSYgkXTh 1HKqKTMpBTZZ8H5zcqYEWYBaaWELrDEXeE 1aa5cmqmvQq8YQTEqcTmW7dfBNuFwgdCD

**Comment by Mugen-Kanosei** [comment]
Formatting should look like the following:

claimer.py COINTYPE SOURCETRANSACTIONID SOURCEPRIVATEKEY SOURCEADDRESS DESTINATIONADDRESS

------

claimer.py BTG 4adc427d330497992710feaa32f85c389ef5106f74e7006878bd14b54500dfff 5K2YUVmWfxbmvsNxCsfvArXdGXm7d5DC9pn4yD75k2UaSYgkXTh 1HKqKTMpBTZZ8H5zcqYEWYBaaWELrDEXeE 1aa5cmqmvQq8YQTEqcTmW7dfBNuFwgdCD

**Comment by ymgve** [comment]
Need to provide more details to see what the issue is.

**Comment by NoWay426** [comment]
I installed Python 2.7, opened and entered this into command prompt:

claimer.py BPA a4da03bb8a76f2b351389bf3b9f43ebd6fc6d04671fad9f15bf109954744cc6c <PrivKey> 1EgkR9dmBrVztmwGVw7FM4SnEYHJ2efHRZ PHxn4f8htXkSU9gvr7hFskX2huEjmciL9m

PrivKey redacted for security, obviously

Have tried using the standalone mode also:

claimer.py BPA a4da03bb8a76f2b351389bf3b9f43ebd6fc6d04671fad9f15bf109954744cc6c <PrivKey> 1EgkR9dmBrVztmwGVw7FM4SnEYHJ2efHRZ PHxn4f8htXkSU9gvr7hFskX2huEjmciL9m --txindex 0 --satoshis 1595124818

**Comment by ymgve** [comment]
You are not supposed to use it from a Python console, you are supposed to use it from the OS command prompt.

**Comment by NoWay426** [comment]
In Windows 10, Win + R opens command prompt 

Input script there - with Python open I'm assuming? - "windows cannot find claimer.py"

Again, thanks for bearing with me, completely new to this

**Comment by ymgve** [comment]
You have to open "cmd.exe" then navigate to the folder where the script is installed inside the command line prompt window

https://www.digitalcitizen.life/command-prompt-how-use-basic-commands

Then you run "claimer.py BPA a4da........" directly in the command line prompt window

**Comment by NoWay426** [comment]
Thank you! I got my BPA. Very happy I won't have to sync anymore blockchains for days. You are awesome.
