### ISSUE TITLE
standalone mode:  --txindex

### ISSUE THREAD

**Issue by Golddouble** [ymgve/bitcoin_fork_claimer#21]
In the readme you write, we need for the standalone mode the

> --txindex "output index in transaction"

Question: Where can I find this? Assumed this https://blockchain.info/de/tx/89112b285a9fff7f70f104bbb449f94cd2f6edb407c61b7bbcae26bc596cf52d was the latest transaction before the fork: Where can I find the output index in transaction?

Thank you.

**Comment by ymgve** [comment]
It's not explicitly shown on blockchain.info - the outputs are listed in index order 0, 1, 2, 3.... on the right hand side, so you have to count or use another explorer which shows these details. In your case, the output index depends on which address you want to claim, if it's 3CMCRgEm8HVz3DrWaCCid3vAANE42jcEv9 then the index is 0, if it's 1FaB8ypM8dDtzq2xDzJ4vHdKwZz9DocnV then the index is 1.

As long as you only claim forks and don't try more advanced usage of the script, you don't need to worry about indexes. The information will automatically be found via the blockchain.info API.
