### ISSUE TITLE
Missing parameter in maketx_basicsig

### ISSUE THREAD

**Issue by emanuelelaface** [ymgve/bitcoin_fork_claimer#3]
line 426 reads:

`return self.maketx_segwitsig(sourcetx, sourceidx, sourceh160, sourcesatoshis, sourceprivkey, pubkey, compressed, outscript, fee, keytype)
`

while it should be

`return self.maketx_segwitsig(sourcetx, sourceidx, sourceh160, signscript, sourcesatoshis, sourceprivkey, pubkey, compressed, outscript, fee, keytype)`

**Comment by ymgve** [comment]
Whoops! Sorry! Fixed.
