### ISSUE TITLE
general issues before handing over the file

### ISSUE THREAD

**Issue by vic4445554** [ymgve/bitcoin_fork_claimer#30]
1)can you format the e-mail address so it opens the mail client? (mailto: ...)
2)how to insert pictures efficiently? (can you demo a couple of pics to show how you want them included? Try with a random picture of a book atop the guide
3)Why in the footer I only see "How it works" "Preparation" "The golden rule" and not the following ones (for the guide sublinks)?
4)the particle effect takes a lot of space in desktop mode... can we do something about it?
5)Coinmarketpie doesn't recognise bitpie and as an exchange. Yet the info about Bitpie and Coinomi is prominent for us... Can you think of a fix?
6)The field TRADE FEE is supposed to be a %, can you change it to string? 
7)The field COMMISSION should be named "WITHDRAWAL FEE" - it could be both a fixed amount or a percentage so it should be a string as well
8)When you calculate the coin value, multiply it by the fork ratio. See example of BCX: they have 10k ratio, therefore value yielded should be multiplied by 10k too
9)how to make an inner link from the instructions on home to the "page" with the fork guide?
10) In "home" I added the blueprint for a consultancy page (similar to the "Services" page on forkdrop.io) - can you format it and create it?

**Comment by ymgve** [comment]
These questions have nothing to do with the claimer script, I don't know why you're asking me.

**Comment by vic4445554** [comment]
sorry wrong github. :(
