### ISSUE TITLE
possibility to combine several transactions in one command?

### ISSUE THREAD

**Issue by Golddouble** [ymgve/bitcoin_fork_claimer#32]
When I have to claim forks from one address but with different "source transaction ID"'s:
For example this:
```
claimer.py <cointype> <source transaction ID 1> <source private key 1> <source address 1> <destination address 1>

and afterwards:

claimer.py <cointype> <source transaction ID 2> <source private key 1> <source address 1> <destination address 1>
```
Do I have to start claimer.py twice? 

First start 
claimer.py <cointype> <source transaction ID 1> <source private key 1> <source address 1> <destination address 1>

Then wait until block inclusion; and afterwards start the second command:

claimer.py <cointype> <source transaction ID 2> <source private key 1> <source address 1> <destination address 1>

Or is there a method to start both with one command? For example something like this:
claimer.py <cointype> <source transaction ID 1>, <source transaction ID 2> <source private key 1> <source address 1> <destination address 1>

Or for example
claimer.py <cointype> <source transaction ID 1> <source private key 1> <source address 1> <destination address 1>, <source transaction ID 2> <source private key 1> <source address 1> <destination address 1>

Thank you for your help.

**Comment by ymgve** [comment]
You don't have to wait until a block inclusion, as long as the transaction has gone into the mempool you can just stop the script and start the one for the next TXID.
