### ISSUE TITLE
Transactions with big amount are rejected

### ISSUE THREAD

**Issue by Ghoom** [ymgve/bitcoin_fork_claimer#35]
I think the problem appears above 2147483647 satoshi.
Maybe a problem with cast int, struct.pack...

**Comment by ymgve** [comment]
People have transferred amounts larger than that without any problems. What issue are you having? What's  the command line (without private key) you're using?

**Comment by Ghoom** [comment]
The user tells me that he has the same problem with BCI and BTV with this transaction 399c83a17622338b236509a465696232e837d0c146bbe0f1d73f95ce3efc01ac. All other transactions seem to work.

https://block.bitvote.one/address/1KhMANjE6MQXE27uEkz17N1HeAVyMnWCo7

claimer.py BTV 399c83a17622338b236509a465696232e837d0c146bbe0f1d73f95ce3efc01ac <privatekey> 1KhMANjE6MQXE27uEkz17N1HeAVyMnWCo7 18Q28VKvW9iYxyejg57xbjwKcG5v6kxr5Z

**Comment by ymgve** [comment]
That transaction got spent at https://blockchain.info/tx/3d2eaff098f8c5b8b234ba5e5f71a98e8652c123755b43683a49e130adaa452d at block height 500683, which is before any of those forks happened.
