### ISSUE TITLE
sending coins within the same blockchain?

### ISSUE THREAD

**Issue by douchebanner** [ymgve/bitcoin_fork_claimer#40]
is there any way of doing this?

i already claimed bci using the script to a bci private key but if i wanted to dump it i would have to use the full node wallet, which failed to synchronize for me and i dont want to wait another month for it to sync as they have no light wallet yet.

they announced they would get listed on bitfinex on may first (not holding my breath) so if it actually does and gets a decent price i wont be able to dump.

is there any way of doing it with the current script or would it need a thorough rewrite?

thanks.

**Comment by ymgve** [comment]
That has been fully supported from the start - after all, you are already sending coins on the same blockchain when originally claiming. The important thing is that you need the TXID and txindex and the exact amount being sent, so you need to find those details on a block explorer or something.
