### ISSUE TITLE
Problem with BTH, BCI claim

### ISSUE THREAD

**Issue by hzfangda** [ymgve/bitcoin_fork_claimer#43]
Thank you for your great work！
I have successfully claimed BCX, BTX using this python script file, but have problems with BTH  and BCI .

**# BTH**
YOU ARE ABOUT TO SEND 1139.91000000 BTH (equivalent to 11.39910000 BTC) FROM _(1HRU.......my address)_
    1139.90900000 BTH (equivalent to 11.39909000 BTC) TO HTiKbtCMSFkVJfjN7Pf62Hxq2racC4r28C
!!! 0.00100000 BTH (equivalent to 0.00001000 BTC) WILL BE SENT AS FEES! CONTINUE AT YOUR OWN RISK !!!

Write 'I am sending coins on the Bitcoin Hot network and I accept the risks' to continue
I am sending coins on the Bitcoin Hot network and I accept the risks
generated transaction aee326449c0691017e658cd16fb2a22283081e3383272083f1a3c10473014584

Connecting to servers and pushing transaction
Please wait for a minute before stopping the script to see if it entered the server mempool.
Connecting to ('seed-jp.bitcoinhot.co', 8222) ...       **Connection failed with: timeout('timed out',)**
        Will retry 100 more times.
Connecting to ('seed-hk.bitcoinhot.co', 8222) ...       Connection failed with: timeout('timed out',)
        Will retry 99 more times.
Connecting to ('seed-uk.bitcoinhot.co', 8222) ...       Connection failed with: gaierror(11001, 'getaddrinfo failed')
        Will retry 98 more times.
Connecting to ('seed-cn.bitcoinhot.co', 8222) ...       Connection failed with: timeout('timed out',)
        Will retry 97 more times.
Connecting to ('seed-us.bitcoinhot.co', 8222) ...       Connection failed with: timeout('timed out',)
        Will retry 96 more times.
Connecting to ('seed-jp.bitcoinhot.co', 8222) ...       Connection failed with: timeout('timed out',)
        Will retry 95 more times.
*************************
************************
        Will retry 3 more times.
Connecting to ('seed-jp.bitcoinhot.co', 8222) ...       Connection failed with: timeout('timed out',)
        Will retry 2 more times.
Connecting to ('seed-hk.bitcoinhot.co', 8222) ...       Connection failed with: timeout('timed out',)
        Will retry 1 more times.
Connecting to ('seed-uk.bitcoinhot.co', 8222) ...
Traceback (most recent call last):
  File "D:\bitcoin_fork_claimer-master\claimer.py", line 1467, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "D:\bitcoin_fork_claimer-master\claimer.py", line 466, in send_tx
    self.sc = socket.create_connection(address, 10)
  File "C:\Python27\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 11001] getaddrinfo failed

**# BCI**
generated transaction 4e12751178a2be1afa41abe0abf7c31bd8ccd33e64ce19386e6207d0d8c9b8f0

Connecting to servers and pushing transaction
Please wait for a minute before stopping the script to see if it entered the server mempool.

Connecting to ('seeder1.bci-server.com', 8331) ...      Connection failed with: error(10061, '')
        Will retry 100 more times.
Connecting to ('seeder2.bci-server.com', 8331) ...      Connection failed with: error(10061, '')
        Will retry 99 more times.
Connecting to ('seeder3.bci-server.com', 8331) ...      Connection failed with: error(10061, '')
        Will retry 98 more times.
Connecting to ('74.208.166.57', 8331) ... SUCCESS, connected to ('74.208.166.57', 8331)
---> 'version' (93 bytes)
<--- 'version' (113 bytes)
     Version information:
        protocol version 70016
        services 13
        timestamp Mon May 21 07:40:22 2018
        user agent '/Bitcoin Interest:0.15.0.1/'
        block height 526109
---> 'verack' (0 bytes)
<--- 'verack' (0 bytes)
<--- 'sendheaders' (0 bytes)
---> 'headers' (1 bytes)
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'inv' (37 bytes)
---> 'mempool' (0 bytes)
<--- 'addr' (31 bytes)
        Got peer address: 74.208.166.57:8331
<--- 'feefilter' (8 bytes)
        server requires minimum fee of 1000 satoshis
        our fee is >= minimum fee, so should be OK
<--- 'getdata' (37 bytes)
        Peer requesting transaction details for 4e12751178a2be1afa41abe0abf7c31bd8ccd33e64ce19386e6207d0d8c9b8f0
---> 'tx' (192 bytes)
        SENT TRANSACTION: 4e12751178a2be1afa41abe0abf7c31bd8ccd33e64ce19386e6207d0d8c9b8f0
<--- 'getdata' (37 bytes)
        Received getdata without our txhash. The transaction may have been rejected.
        This script will retransmit the transaction and monitor the mempool for a few minutes before giving up.
<--- 'inv' (73 bytes)
        transaction: 48b584d88f4c2ec83fbe55e5e685c3b64e9de588cd41c49bcafd05b734913142
        transaction: 7a9f4041cfe5945993168e5e4940d01a96b8719f91c2f2c6456220bdee27eafa

        Our transaction was not found in the mempool.
        Will retransmit and check again 4 more times.
************************
************************
       Our transaction was not found in the mempool.
       Traceback (most recent call last):
  File "D:\bitcoin_fork_claimer-master\claimer.py", line 1467, in <module>
    client.send_tx(txhash, tx, args.fee)
  File "D:\bitcoin_fork_claimer-master\claimer.py", line 571, in send_tx
    raise Exception("\tGiving up on transaction. Please verify that the inputs have not already been spent.")
Exception:      Giving up on transaction. **Please verify that the inputs have not already been spent.**

**Of course,  I have not already been spent or claimed BCI.**

Thank you!

**Comment by ymgve** [comment]
Bitcoin Hot seems to be doing a "network upgrade" according to https://bithot.org/ - seems like they've taken down the network and haven't brought it back up. They also removed the wallet download from their site.

I can not provide more support for Bitcoin Interest unless you provide the exact TXID and address you're trying to claim from.

**Comment by hzfangda** [comment]
thank your reply.
