### ISSUE TITLE
BCD functionality isn't working, found fix

### ISSUE THREAD

**Issue by cryptolapin** [ymgve/bitcoin_fork_claimer#46]
seed1.dns.btcd.io seed2.dns.btcd.io.... isn't working. just change for 139.198.190.221 in line 820 and the tx will be broadcasted.

Connecting to ('seed4.btcd.io', 7117) ... 	Connection failed with: gaierror(8, 'nodename nor servname provided, or not known')
	Will retry 98 more times.
 then voila

Connecting to ('139.198.190.221', 7117) ... SUCCESS, connected to ('139.198.190.221', 7117)
---> 'version' (93 bytes)
<--- 'version' (110 bytes)
     Version information:
	protocol version 70015
	services 13
	timestamp Tue May 22 14:12:42 2018
	user agent '/Bitcoin Diamond:0.14.2/'
	block height 517968

**Comment by ymgve** [comment]
Added this and the other peer IPs found in https://github.com/eveybcd/BitcoinDiamond/blob/master/src/chainparamsseeds.h
