### ISSUE TITLE
BTCP

### ISSUE THREAD

**Issue by SanderM22** [ymgve/bitcoin_fork_claimer#48]
Can we claim BTCP with this script and send directly to a BTCP address (an exchange for example) when it's coming from a segwit address? Or do we need to send to a Z-address first?

When claiming it using the BTCP core wallet we can't send it to a BTCP address directly. It has to be sent to a Z-address first and from there to a BTCP address.

**Comment by fazlearefin** [comment]
I have claimed BTCP and could directly send to a BTCP exchange without using any Z-address first. And yes, all of them were coming from a segwit address. I tried the Electrum BTCP wallet and also the BTCP full node wallet. They both suck. This bitcoin_fork_claimer worked like a charm.

**Comment by ymgve** [comment]
Script does not use or understand Z-addresses at all. Sending to/from segwit/non-segwit is working just like in other forks.
