### ISSUE TITLE
WBTC address not recognized

### ISSUE THREAD

**Issue by fazlearefin** [ymgve/bitcoin_fork_claimer#49]
When trying to send to a WBTC address (e.g. `WTfvVSuE6fKGyG7Kf5uxoSjuH9jcw37MDK`), I get this error

```
Exception: The destination address WTfvVSuE6fKGyG7Kf5uxoSjuH9jcw37MDK does not match BTC or WBTC. Are you sure you got the right one?
```

**Comment by ymgve** [comment]
There are two WBTCs, one fork and one altcoin. The one on tradesatoshi (I assume that's what you're using) is the altcoin.
