### ISSUE TITLE
Crash on get trx info

### ISSUE THREAD

**Issue by LeaTex** [ymgve/bitcoin_fork_claimer#50]
This was the only with problem in a set of 20 addresses.

Address: 1E4vfzJBS4jPvHewpGB7Z59cQ6ezvsHkHM

Error:
```
  File "claimer.py", line 1324, in <module>
    txindex, bciscript, satoshis = get_tx_details_from_blockchaininfo(args.txid, args.srcaddr, coin.hardforkheight)
  File "claimer.py", line 327, in get_tx_details_from_blockchaininfo
    if outinfo["addr"] == addr:
KeyError: 'addr'
```

Got the same error for any coin.

Command:
```
python2.7 claimer.py SBTC 1a08c68c543b2c78a63ba78bd3b97484d7cd10f6fb082fd264a8b2380c39926e PRIVKEY 1E4vfzJBS4jPvHewpGB7Z59cQ6ezvsHkHM 18X1pEg48ETzLf44sPPhaQCiqWjGTP7ALq
```

**Comment by ymgve** [comment]
Problem was that transaction had one output that blockchain.info couldn't decode into an address, which the script didn't account for.

Fixed with https://github.com/ymgve/bitcoin_fork_claimer/commit/2a0ae4d11f272d7a9e9bcd805d0ec8af6962add1

**Comment by LeaTex** [comment]
Cool!
Should I make a new pull to get this fix?
I will tray. Thanks
