### ISSUE TITLE
BCL claiming problem

### ISSUE THREAD

**Issue by talesfromthecrypt** [ymgve/bitcoin_fork_claimer#51]
Hi i am trying to claim BCL and here is what the response i get in the terminal%

Connecting to ('seed.bitcoinclean.org', 8338) ... SUCCESS, connected to ('195.201.119.226', 8338)
---> 'version' (93 bytes)
<--- 'version' (107 bytes)
     Version information:
	protocol version 70015
	services 1037
	timestamp Mon May 28 06:56:06 2018
	user agent '/LittleGlobe:0.15.99/'
	block height 565108
---> 'verack' (0 bytes)
<--- 'verack' (0 bytes)
<--- 'sendheaders' (0 bytes)
---> 'headers' (1 bytes)
<--- 'sendcmpct' (9 bytes)
<--- 'sendcmpct' (9 bytes)
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'inv' (37 bytes)
---> 'mempool' (0 bytes)
<--- 'addr' (31 bytes)
	Got peer address: 195.201.119.226:8338
<--- 'feefilter' (8 bytes)
	server requires minimum fee of 1000 satoshis
	our fee is >= minimum fee, so should be OK
<--- 'getdata' (37 bytes)
	Peer requesting transaction details for 735c1af55cf450bb6aaf512c8c68444adaa29d71fe99308b52693d39938663dc
---> 'tx' (190 bytes)
	SENT TRANSACTION: 735c1af55cf450bb6aaf512c8c68444adaa29d71fe99308b52693d39938663dc
<--- 'getdata' (37 bytes)
	Received getdata without our txhash. The transaction may have been rejected.
	This script will retransmit the transaction and monitor the mempool for a few minutes before giving up.
<--- 'ping' (8 bytes)
---> 'pong' (8 bytes)
---> 'tx' (190 bytes)
	Re-sent transaction: 735c1af55cf450bb6aaf512c8c68444adaa29d71fe99308b52693d39938663dc
---> 'mempool' (0 bytes)

**Comment by ymgve** [comment]
What's the TXID and address you're trying to claim from?

**Comment by ymgve** [comment]
That output was spend in this transaction https://blockchain.info/tx/1468cc44b40dbc41452575c96767b7cc771c980facc7dd228522a9be5fd67579 at block height 510512, which was before the fork height for BCL at height 518800. At the time of the fork, the address was empty.

**Comment by talesfromthecrypt** [comment]
Yes, i guess it was incoming transaction and the funds were on this address until the fork

**Comment by talesfromthecrypt** [comment]
Ok, i resolved it, thank you for support!
