### ISSUE TITLE
Copay wallet

### ISSUE THREAD

**Issue by KEVORK890** [ymgve/bitcoin_fork_claimer#52]
Hi,
is it possible to claim the forked coins from a copay wallet? Thanks

**Comment by ymgve** [comment]
I don't know anything about what a copay wallet is. Could you give some more details? What is the format of the private key of that wallet?

**Comment by KEVORK890** [comment]
Actually it's a multisig wallet, so it worked perfectly. Many thanks!

**Comment by ymgve** [comment]
That's weird, since my script doesn't support multisig.

**Comment by KEVORK890** [comment]
I have retrieved the various wallets and used the associated private and public keys.
