### ISSUE TITLE
BCL claim issue

### ISSUE THREAD

**Issue by fabioganga** [ymgve/bitcoin_fork_claimer#55]
Hi, I am trying to claim Bitcoin Clean (BCL) and I am receiving this warning, please tell me if I should proceed or not (my BTC address starts with 3 and so does the Yobit address where I would like to deposit... so I assume they are both Segwit addresses?):

YOU ARE TRYING TO SEND TO A P2SH ADDRESS! THIS IS NOT NORMAL! Are you sure you know what you're doing?

Write 'I am aware that the destination address is P2SH' to continue

Thanks a lot for your help.

**Comment by ymgve** [comment]
Yeah, it means you're trying to send TO a segwit address, which rarely happens for altcoins. I would dobule check that you're actually depositing to a BCL address on Yobit, since it seems a bit strange that they're giving out Segwit addresses for depositing.

**Comment by fabioganga** [comment]
Hi, thanks for your reply. I have double checked on Yobit, it seems like they are issuing a Segwit address starting with 3.... please see this screenshot:
http://tinypic.com/r/2nqqkx3/9
Would it be safe to continue, in your opinion? Thanks.

**Comment by ymgve** [comment]
Late reply, but P2SH is also used for multisig and other more advanced script uses besides segwit. So if the exchange tells you to send to a 3.... address, try with a smaller amount to verify that it works, then the larger amount. The script supports multiple destination addresses now, so you can "chip off" a small amount to test send, then just send the rest back to yourself. Remember to note down your generated TXID, though, as you have to use that in the next run of the script.
