### ISSUE TITLE
Add support for Bitcoin File (BIFI) please

### ISSUE THREAD

**Issue by fazlearefin** [ymgve/bitcoin_fork_claimer#57]
Some exchanges have started accepting Bitcoin File (BIFI) deposits. Please add support for BIFI. BIFI repo has just been released a couple of days ago here https://github.com/bitcoinfile/bitcoinfile

**Comment by Ghoom** [comment]
class BitcoinFile(BitcoinFork):
    def __init__(self):
        BitcoinFork.__init__(self)
        self.ticker = "BIFI"
        self.fullname = "BitcoinFile"
        self.hardforkheight = 501225
        self.magic = 0xd8c42ef8
        self.port = 10698
        self.seeds = ("dnsseed1.bitcoinfile.org", "dnsseed2.bitcoinfile.org", "dnsseed3.bitcoinfile.org", "dnsseed4.bitcoinfile.org", "dnsseed5.bitcoinfile.org", "dnsseed6.bitcoinfile.org", "dnsseed7.bitcoinfile.org", "dnsseed8.bitcoinfile.org", "dnsseed9.bitcoinfile.org")
        self.maketx = self.maketx_basicsig
        self.signtype = 0x01
        self.signid = self.signtype
        self.txversion = 20
        self.BCDgarbage = struct.pack("<I", 20)
        self.coinratio = 1000.0

**Comment by fazlearefin** [comment]
Thanks @Ghoom . The `init` function name needed to be modified to `__init__` to make it work. I have submitted a pull request https://github.com/ymgve/bitcoin_fork_claimer/pull/60

For people trying to sell their useless BIFI, you can sell it at this exchange https://gate.io

**Comment by ymgve** [comment]
Merged into master branch now. Thanks!
