### ISSUE TITLE
Tutorial on using ymgve/bitcoin_fork_claimer

### ISSUE THREAD

**Issue by fazlearefin** [ymgve/bitcoin_fork_claimer#62]
I've written an easy to follow tutorial on using `ymgve/bitcoin_fork_claimer` to claim bitcoin forks. It might be helpful for people who are planning on claiming the forks. Maybe it can be linked from the `README.md` of `ymgve/bitcoin_fork_claimer`.

The tutorials are available here https://steemit.com/bitcoin/@thegripmaster/bitcoin-fork-claim-guide-or-claim-your-forked-bitcoins-from-trezor-ledger-nano-keepkey and https://github.com/fazlearefin/bitcoin-fork-claim-guide

**Comment by Steve132** [comment]
While I don't see a lot of problems with this technically, don't you think it's kind of dangerous to advise people to put their hardware mnemonic into a webpage on a hot computer?  Doesn't that really defeat the purpose of a hardware wallet?  I feel like you need to have some more disclaimers about how intrinsically dangerous this is!

**Comment by fazlearefin** [comment]
@Steve132 Thanks for your input. I have updated the First Steps, 01. Generate the list of Path/Address/Public Key/Private Key, and Disclaimer sections on the dangers of not creating a new wallet and transferring the BTC to the new wallet before starting the fork claim.

**Comment by forkdrop** [comment]
Also, advising people to use findmycoins.ninja can be used to correlate their balances with their browser session and/or IP address. This is something we do not advise at forkdrop for this reason. https://forkdrop.io/#table-exchanges shows which exchanges are actually open for deposit for various coins and tracks the KYC status.

**Comment by avialias** [comment]
I have few Q.

I have btc on non sw address in Ledger. Do I have to move it to sw address
to be able to pay smaller fees now and to use Lighting network?

How to do it in most secured way

**Comment by avialias** [comment]
Thx guys.

Always ready to read some tutorials. ;)

Hodl...just hodl...it will go back...
I know...I'm in from 2011. I survived lots of bumps and dumps...
I survived Mt Gox... Lost then 5btc...wounded will I get it ever back...

Invest smart...read about IRS laws..and mining and collecting forks...

;)

This is like television technology... It passed 40years before it was
globally accepted...same here...

In 2011 on bitcoin forum was joke...
Grandson to grampa: Grandpa You had 1 whole BTC?
Yes, son...

**Comment by fazlearefin** [comment]
I just want to add that most of the BTC forks, except BCH, aren't worth shit to risk your precious BTC. So if you are unsure of what you are doing, stay out of trying to get the free forks of BTC.

**Comment by forkdrop** [comment]
We have a bunch of guides for Forkdrop Suite at: https://forkdrop.io/suite
If you have a number of addresses and balances, following the Intermediate's guide is advisable: https://forkdrop.io/intermediates-guide-to-efficient-forked-bitcoin-value-claiming-record-keeping

By the by, blockchain.info's .onion gateway is down this week which is defeating `claim-prep.py` and I am working on a patch to utilize Electrum servers via Tor instead. That should be ready in a day or two. Will announce on twitter.com/forkdrop
